install:
  - firely_terminal
  - sushi
  - igpub
  - publishtools
  - igtools
deploy:
  env:
    dev: gematik_gemspec_fhir_dev-0
    prod: gematik_gemspec_fhir_prod-0
build:
  builtin:
    igtools: true
  pipeline:
    - requirements
    - shell: reqtools polarion ./input/content
    - sushi
    - igpub
    - igpub_qa
