id: de.gematik.ti
canonical: https://gematik.de/fhir/ti

name: gemIG_TI_Common
title: "Implementation Guide TI Common"
jurisdiction: "urn:iso:std:iso:3166#DE"
license: Apache-2.0
language: de

experimental: false
status: draft # draft | active | retired | unknown
version: 1.5.0-ballot.1
date: 2026-09-15

copyrightYear: 2026+
copyright: gematik GmbH / Dieser Implementation Guide ist lizenziert unter [Apache License](./license.html), Version 2.0.
#Flip releaseLabel to 'release' for publication. Flip to 'ci-build' for CI
releaseLabel: ci-build  # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use

fhirVersion: 4.0.1

publisher:
  name: gematik GmbH
  url: https://www.gematik.de
  email: patientteam [ at ] gematik.de

dependencies:
  hl7.fhir.uv.xver-r5.r4: latest
  # Temporary dependency required to resolve a preferred binding to an IPS ValueSet referenced by EU Core.
  hl7.fhir.uv.ips: 2.0.1
  de.basisprofil.r4: 1.6.0
  de.fhir.medication: 1.0.7
  ihe.iti.mhd: 4.2.3
  hl7.fhir.eu.extensions.r4: 1.3.0
  hl7.fhir.eu.base: 2.0.0
  hl7.fhir.eu.laboratory: 2.0.0

# FSHOnly: true

pages:
  index.md:
    title: Home
  general-principles.md:
    title: "Generelle Prinzipien"
  actors.md:
    title: Akteure
  document-management.md:
    title: IHE MHD-basiertes Dokumentenmanagement in der TI
  validation.md:
    title: "Validierung"
  query-api-search.md:
    title: "Query API: Allgemeine Anforderungen Suche und Sortierung"
  query-api-paging.md:
    title: "Query API: Allgemeine Anforderungen Paginierung"
  fhir-format.md:
    title: "FHIR-Formatserialisierung"

  # artifacts.md:
  #   title: "FHIR-Artefakte"
  artifacts-common.md:
    title: "Common-Artefakte"
  artifacts-actors.md:
    title: "Artefakte für Akteure"
  artifacts-dgmp.md:
    title: "Artefakte für den Medikationsprozess (dgMP)"
  artifacts-document.md:
    title: "Artefakte für das Dokumentenmanagement"
  artifacts-behavior.md:
    title: "Artefakte für das Verhalten"
  artifacts-laboratory.md:
    title: "Artefakte für den LaborLaborprozess"
  referenced.md:
    title: "Referenzen"
  downloads.md:
    title: "Downloads"
  release-notes.md:
    title: "Release Notes"
  dependencies.md:
    title: Abhängigkeiten
  spec-sheet.md:
    title: "Anforderungslisten"
    actor-epa-medication.md:
      title: "Anforderungsliste: ePA Medication Service"
    actor-epa-audit.md:
      title: "Anforderungsliste: ePA Audit Event Service"
    actor-epa-patient.md:
      title: "Anforderungsliste: ePA Patient Service"
    actor-epa-mhd.md:
      title: "Anforderungsliste: ePA MHD Service"
    actor-epa-client.md:
      title: "Anforderungsliste: ePA PS / ePA-Client-Systeme / ePA-FdV"
    actor-tiflow.md:
      title: "Anforderungsliste: TI-Flow Fachdienst"
    actor-vsdm.md:
      title: "Anforderungsliste: VSDM 2.0"
  comparisons.md:
    title: "Versionsvergleiche"
  license.md:
    title: "Apache License"


menu:
  Home: index.html
  Generelle Prinzipien:
    Generelle Prinzipien: general-principles.html
    "Akteure und Obligations": actors.html
    Dokumentenmanagement: document-management.html
    Validierung: validation.html
  Schnittstellen:
    "Query API: Paginierung": query-api-paging.html
    "Query API: Suche / Sortierung": query-api-search.html
    FHIR-Formatserialisierung: fhir-format.html
  Über:
    Referenzen: referenced.html
    Downloads: downloads.html
    Abhängigkeiten: dependencies.html
    Release Notes: release-notes.html
    Anforderungslisten: spec-sheet.html
    Versionsvergleiche: comparisons.html
    Lizenz: license.html
  FHIR-Artefakte:
    Übersicht: artifacts.html
    "Akteure": artifacts-actors.html
    Common: artifacts-common.html
    "Medikationsprozess (dgMP)": artifacts-dgmp.html
    Dokumentenmanagement: artifacts-document.html
    Verhalten: artifacts-behavior.html
    Laborprozess: artifacts-laboratory.html

# https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
parameters:
  shownav: true
  apply-version: false
  default-version: true
  apply-publisher: false
  default-publisher: true
  apply-contact: false
  default-contact: true
  no-usage-check: true
  show-inherited-invariants: true
  excludettl: true
  i18n-default-lang: de
  ips-comparison: 2.0.1
  # For which versions comparisons should be generated.
  #   {last} - compare with the last published version (whatever it's status)
  #              - this is the default if the parameter doesn't appear
  #   {current} - compare with the last full published version
  #   n/a - don't do any comparison
  #   [v] - a previous version where [v] is the version
  version-comparison:
    # There seem to be an problem when using this flag, maybe 1.1.1-ballot.1 causes issues?
    # - "{current}"
    - 1.0.1
    - 1.1.1
    - 1.2.0
    - 1.3.0
    - 1.3.1
  bundle-references-resolve: false
  no-narrative:
    # "StructureDefinition/*" doesn't seem to work anymore
    - StructureDefinition/*
    - AuditEvent/*
    - Bundle/*
    - OperationOutcome/*
    - Patient/*
  path-resource:
    - fsh-generated/resources
    - extracted/resources
  path-pages:
    - input/intro-notes
    - input/content
  no-validate:
    - MedicationDispense/4e6e1623-778e-44a3-b208-8479f5339e43
    - Bundle/example-history-bundle
    # Validation disabled because the required SNOMED CT version is not available on the terminology server.
    - ValueSet/diagnosis-snomed-ct
  special-url:
    - https://gematik.de/fhir/epa-medication/StructureDefinition/drug-category-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/epa-medication
    - https://gematik.de/fhir/epa-medication/StructureDefinition/epa-medication-pharmaceutical-product
    - https://gematik.de/fhir/epa-medication/StructureDefinition/epa-medication-pzn-ingredient
    - https://gematik.de/fhir/epa-medication/StructureDefinition/epa-medication-type-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/epa-medication-unique-identifier
    - https://gematik.de/fhir/epa-medication/StructureDefinition/medication-formulation-packaging-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/medication-ingredient-amount-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/medication-ingredient-darreichungsform-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/medication-id-vaccine-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/medication-manufacturing-instructions-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/medication-packaging-size-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/medication-total-quantity-formulation-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/rx-originator-process-identifier
    - https://gematik.de/fhir/epa-medication/StructureDefinition/rx-prescription-process-identifier
    - https://gematik.de/fhir/epa-medication/StructureDefinition/rx-prescription-process-identifier-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/indicator-bvg-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/multiple-prescription-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/narcotics-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/patient-id-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/prescriber-id-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/teratogenic-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/indicator-ser-extension
    - https://gematik.de/fhir/epa-medication/StructureDefinition/context-extension
    - https://gematik.de/fhir/epa-medication/CodeSystem/context-code


# groups:
#   DgMPProfiles:
#     name: Medikationsprozess dgMP
#     description: Base profiles for the European context.
#     resources:
#       - StructureDefinition/ti-medication-dgmp
#       - StructureDefinition/ti-medication-dispense-dgmp
#       - StructureDefinition/ti-medication-request-dgmp
#       - StructureDefinition/ti-medication-statement-dgmp
#       - StructureDefinition/drug-category-extension
#       - StructureDefinition/epa-medication-type-extension
#       - StructureDefinition/indicator-bvg-extension
#       - StructureDefinition/indicator-ser-extension
#       - StructureDefinition/medication-formulation-packaging-extension
#       - StructureDefinition/medication-ingredient-amount-extension
#       - StructureDefinition/teratogenic-extension
#       - StructureDefinition/rx-prescription-process-identifier-extension
#       - StructureDefinition/prescriber-id-extension
#       - StructureDefinition/patient-id-extension
#       - StructureDefinition/narcotics-extension
#       - StructureDefinition/multiple-prescription-extension
#       - StructureDefinition/medication-total-quantity-formulation-extension
#       - StructureDefinition/medication-packaging-size-extension
#       - StructureDefinition/medication-manufacturing-instructions-extension
#       - StructureDefinition/medication-is-vaccine-extension
#       - StructureDefinition/medication-ingredient-darreichungsform-extension
#       - StructureDefinition/context-extension
#       - StructureDefinition/e-prescription-id
#       - StructureDefinition/medication-plan-identifier
#       - StructureDefinition/epa-medication-unique-identifier
#       - StructureDefinition/rx-prescription-process-identifier
#       - StructureDefinition/rx-originator-process-identifier
#       - CodeSystem/context-code
#       - ValueSet/context-code


instanceOptions:
  # When set to true, slices must be referred to by name and not only by a numeric index in order to be used
  # in an Instance's assignment rule. All slices appear in the order in which they are specified in FSH rules.
  # While SUSHI defaults to false for legacy reasons, manualSliceOrding is recommended for new projects.
  manualSliceOrdering: true # true | false
  # Determines for which types of Instances SUSHI will automatically set meta.profile
  # if InstanceOf references a profile:
  # setMetaProfile: always # always | never | inline-only | standalone-only
  #
  # Determines for which types of Instances SUSHI will automatically set id
  # if InstanceOf references a profile:
  # setId: always # always | standalone-only
  