Extension: RxPrescriptionProcessIdentifierExtension
Id: rx-prescription-process-identifier-extension
Description: "This extension is used to track medication prescription transactions between the E-Rezept-Fachdienst and the ePA. The RxPrescriptionProcessIdentifier is generated by the ePA Medication Service and consists of the PrescriptionId and the authoredOn date of the operation parameters request. It ensures consistent referencing and management of medication-related resources across different systems."
* insert Meta
* ^url = "https://gematik.de/fhir/epa-medication/StructureDefinition/rx-prescription-process-identifier-extension"
// preserve the version
* ^version = "1.0.6-2"
* ^date = "2025-05-12"
* ^status = #active

* value[x] only Identifier
* valueIdentifier 1..1
* valueIdentifier only RxPrescriptionProcessIdentifier
