ValueSet: LaboruntersuchungsgruppeVS
Id: laboruntersuchungsgruppe
Title: "Test-Profil Laboruntersuchungsgruppe"
Description: "Dieses Valueset enthält die Codes zur Beschreibung von Test-Profil Laboruntersuchungsgruppe."
* TestProfileCS#haemato "Hämatologie"
* TestProfileCS#baselec "Basisanalytik - Elektrolyte"
* TestProfileCS#baskidn "Basisanalytik - Nierenfunktion"
* TestProfileCS#baslivr "Basisanalytik - Leberfunktion"
* TestProfileCS#basenzy "Basisanalytik - Enzyme"
* TestProfileCS#endocr "Endokrinologie"
* TestProfileCS#cardio "Kardiologie"
* TestProfileCS#lipmetb "Fettstoffwechsel"
* TestProfileCS#diabdiag "Diabetesdiagnostik"
* TestProfileCS#vitdiag "Vitamindiagnostik"
* TestProfileCS#inflmark "Entzündungsmarker"
* TestProfileCS#proteins "Proteine"
* TestProfileCS#hemostas "Hämostaseologie"
* TestProfileCS#uridiag "Urindiagnostik"
* TestProfileCS#ironmetb "Eisen-/Hämoglobinstoffwechsel"